development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: <%= ENV['REDIS_URL'] %>
  host: ec2-34-201-226-230.compute-1.amazonaws.com
  port: 33949
  password: p37aed715f0aa992603c3a8b0281ed3644c1f9aa59f12c92648dc18210ea6da3f
  channel_prefix: auction_house_production
